#!/usr/bin/env bash
# This script configure Nginx so that its HTTP response contains a custom header (X-Served-By) on web-01 and web-02
sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

# create redirect for /rediret_me then add header to display hostname 
new_string="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/tekbro.tech permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# create redirect for error page
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
