#!/usr/bin/env bash
# list of ufw commands that used

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw disable
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw default deny incoming

